### ISSUE TITLE
Custom Separator Q.

### ISSUE THREAD

**Issue by Aur0nd** [replete/obsidian-minimal-theme-css-snippets#1]
Hey @replete first of all thank you for OpenSourcing the repo - honestly much appreciated!

I was wondering if you could help me with the custom separators?

It doesn't seem to be working and I cannot figure out why
![image](https://user-images.githubusercontent.com/71910902/223666434-367017c6-622a-4f2e-b358-35811db5af6a.png)

OS: Linux
v1.1.16

**Comment by replete** [comment]
It's a CSS hack, so you have to edit the CSS file to suit your specific file system hierarchy. 

If it is still not working with correct CSS, the version of Electron probably does not support `:has` operator. This was introduced in 1.1.8 in Mac/Windows. There actually was a problem with this for users of the homebrew package manager on mac, I had 1.1.9 but the version of electron was from earlier.

**Comment by replete** [comment]
I just saw your use of '===' in sortspec. That's not how it works, dupe/edit the CSS and adjust accordingly, 

e.g.

```css
.nav-folder-children > [class*=nav-]:has([data-path="AWS.])::after,
.nav-folder-children > [class*=nav-]:has([data-path="DNS"])::after
{
...
```

**Comment by replete** [comment]
Apologies, it got a bit confusing because I was asking the File Explorer Custom Sorting plugin owner to add the separators feature. He didn't want to because it was complicated to mess with the File Explorer UI, so I wrote this hack, he updated his README, and left the initial discussion lying around...
