### ISSUE TITLE
What is the plugin in the screenshot ?

### ISSUE THREAD

**Issue by ZhymabekRoman** [replete/obsidian-minimal-theme-css-snippets#2]
I would like to ask about the functionality on the left side of the screenshot, with sub-items "Goals", "Aarchive", and etc. - how to make such and if it is a plugin, what is it called?  I tried to find the plugin itself from the list, but could not find it. Thank you very much!

**Comment by replete** [comment]
- File Explorer Custom Sorting plugin
- Icon Folders plugin
- Compact Sidebar snippet (in this repo)

**Comment by replete** [comment]
My `sortspec` (config file for File Explorer Custom Sorting):
```
---
sorting-spec: |
    target-folder: Daily
    > a-z
    /--hide: Daily.md
    target-folder: /
    Inbox
    Scratchpad
    Goals
    Projects
    Tasks
    Focus
    Tracker
    Daily
    Weekly
    Journal
    Dreams
    Thoughts
    Notes
    Reference
    Writing
    People
    Authors
    Archive
    Assets
    /--hide: Context
    ...
    z-a
    target-folder: Authors
    a-z
---
```
