### ISSUE TITLE
Custom Separators and Compact File Explorer not rendering correctly

### ISSUE THREAD

**Issue by derekhlindell** [replete/obsidian-minimal-theme-css-snippets#5]
Hey! From the examples was stoked on this, work looks awesome. Unfortunately for me, it's currently not working properly for the Custom Separator or the Compact File Explorer as the CSS seems to be off. 

![image](https://github.com/replete/obsidian-minimal-theme-css-snippets/assets/15840123/3312839b-7038-4a1c-ac7b-caf84d355471)

I'm on Windows 10, Obsidian 1.4.16 and Minimal 7.3.2

**Comment by replete** [comment]
Thanks for the info. 

I've just updated to Obsidian 1.14.16 and Minimal 7.3.2, everything looks good here.

Two things that would cause this:

1. Old installer version of Obsidian (see note in README)

- What version of installer do you see in 'About Obsidian?

2. Conflicting styles from another plugin (which I don't use, see list in README) or CSS snippet

Could you let me know if the problem persists after:

- disabling community plugins (exluding mysnippets if you followed my advice in README) and restarting Obsidian
- doing the above and disabling other CSS snippets

**Comment by replete** [comment]
@derekhlindell Any progress?

**Comment by replete** [comment]
Closing as @derekhlindell didn't respond
