### ISSUE TITLE
Make.MD Inline Context not Compacting/Tidying

### ISSUE THREAD

**Issue by JLeeAgency** [replete/obsidian-minimal-theme-css-snippets#6]
Hey, thanks a ton for putting out these snippets; I'm using a lot of them and it's made a huge difference for my layout, looks WAY better. But the biggest thing bugging me is the "Make.MD Inline Context" snippet.

In place of where I see you have a "Add tag" button, I'm seeing a "Pin to Space" button. Also, I see in your screenshot that the snippet should be hiding properties/contexts that have an empty or 0 value, but mine still show. What are your Make.MD settings/Minimal/Style plugin settings at? At least the ones related to contexts/properties I mean.

![image](https://github.com/replete/obsidian-minimal-theme-css-snippets/assets/149766627/5542166c-35a9-48f3-9143-f9898e5f6d64)

I'm on Windows 11, Obsidian v1.5.3 (installer v1.5.3), Minimal 7.4.7

**Comment by replete** [comment]
Glad its useful to you. I'm afraid my documentation is not ideal, but I think I did mention I'm only using Make.MD for the banner functionality only, so I have spaces disabled. I've attached screenshots of my Make.MD settings here. I don't use minimal style settings at all.

![Screenshot 2024-01-08 at 00 39 14](https://github.com/replete/obsidian-minimal-theme-css-snippets/assets/812139/104f9cf6-6f0d-48a9-932e-04a07a4973ac)
![Screenshot 2024-01-08 at 00 39 30](https://github.com/replete/obsidian-minimal-theme-css-snippets/assets/812139/8386638a-5658-459c-be0b-17bf40dc6279)
![Screenshot 2024-01-08 at 00 39 41](https://github.com/replete/obsidian-minimal-theme-css-snippets/assets/812139/b3d1c3f9-cc24-4cf4-ba95-a6106f9fa758)

This repo could be a lot better but I just don't have the time to refine it towards something that non-technical end-users can just get on with and maintain it, but I've tried to make it straightforward enough. Obsidian has changed a fair bit and as features overlap with community plugins a few things have moved around such as Make.MD and the new Properties feature.

Phil

**Comment by replete** [comment]
Just as an update, I've ended up disabling Make.MD for now because inline contexts have been a buggy mess and not worked properly. All I wanted it for was the banner functionality. I will try again in another version or two to fix it again.
